WIP

diff --git a/taskfile b/taskfile
--- a/taskfile
+++ b/taskfile
@@ -21,13 +21,16 @@ function customize {
       echo "An email is required"
       exit 1
     fi
-    sed -i s/wiki-admin@domain.com/$2/g ./services/wikijs/config.yml
+    sed -i s/wiki-admin@domain.com/$2/g ./docker-compose.yml
   elif [ "$1" == "domain" ] ; then
     if [ "$2" == "" ] ; then
       echo "A domain is required"
       exit 1
     fi
     grep -R example.com . | cut -d':' -f1 | uniq | while read f ; do sed -i s/example.com/$2/g $f ; done
+  else
+    echo "Invalid command"
+    exit 1
   fi
 }
 
